language: python

matrix:
  include:
    - os: linux
      name: linux:deno_testing
    - os: windows
      name: windows:deno_testing

# before_install:

install:
  - curl -L https://deno.land/x/install/install.py | python
  - export PATH=$HOME/.deno/bin:$PATH

script:
  - deno -v
  - deno test/index.spec.ts
