# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

defaults: &defaults
  working_directory: ~/normalize-diacritics
  docker:
    - image: circleci/python:2-node

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Deno
          command: curl -fsSL https://deno.land/x/install/install.sh | sh
      - run:
          name: Add Deno To PATH
          command: |
            echo $BASH_ENV
            echo 'export PATH="$HOME/.deno/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Versions
          command: |
            pwd
            deno -v
      - run:
          name: Test
          command: deno ./mod_test.ts

workflows:
  version: 2
  deno-test:
    jobs:
      - test
